import { StyleSheet } from "react-native";
import useDimensions from "../../../../hooks/useDimensions";
import color from "../../../../utils/colors";
import { font } from "../../../../utils/fonts";
const { heightScreen, widthScreen } = useDimensions();

const FormTrainingStyles = StyleSheet.create({
  modal: {
    flex: 1,
    backgroundColor: "#0000004e",
    justifyContent: "center",
    alignItems: "center",
  },
  viewModalHeader: {
    width: widthScreen * 0.8,
    backgroundColor: color.primary,
    borderTopEndRadius: 10,
    borderTopStartRadius: 10,
    justifyContent: "space-around",
    alignItems: "center",
    height: heightScreen * 0.04,
    flexDirection: "row",
    marginBottom: heightScreen * 0.035,
  },
  textModalHeader: {
    fontSize: font.h2.fontSize,
    fontWeight: font.h2.fontWeight,
    textTransform: "capitalize",
    letterSpacing: 2,
    marginLeft: widthScreen * 0.21,
    marginEnd: widthScreen * 0.08,
  },
  viewModal: {
    backgroundColor: color.secondary,
    width: widthScreen * 0.8,
    justifyContent: "flex-start",
    alignItems: "center",
    borderBottomEndRadius: 10,
    borderBottomStartRadius: 10,
  },
  textModal: { color: color.primary },
  textInput: {
    backgroundColor: color.secondary,
    color: color.primary,
    height: heightScreen * 0.07,
    width: widthScreen * 0.5,
    borderRadius: 10,
    elevation: 2,
    marginVertical: heightScreen * 0.01,
    textAlign: "center",
  },
  label: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: heightScreen * 0.02,
    borderRadius: 5,
  },
  containerLabels: {
    width: widthScreen * 0.7,
  },
  sendTouchOff: {
    backgroundColor: color.secondary,
    width: widthScreen * 0.45,
    height: heightScreen * 0.05,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
    borderColor: color.primary,
    borderWidth: 0.2,
    elevation: 10,
  },
  sendTextOff: { color: color.primary },
  sendTextOn: { color: color.secondary },
  sendTouchOn: {
    backgroundColor: color.primary,
    width: widthScreen * 0.45,
    height: heightScreen * 0.05,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
  },
  viewError: {
    justifyContent: "flex-start",
    alignItems: "center",
    height: widthScreen * 0.08,
    width: widthScreen * 0.45,
  },
  textError: { color: color.redType, fontSize: font.b2.fontSize },
  iconStyle: { width: widthScreen * 0.05, height: widthScreen * 0.05 },
  containerChecks: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: color.secondary,
    width: widthScreen * 0.7,
    height: heightScreen * 0.17,
    borderBottomEndRadius: 5,
    borderBottomStartRadius: 5,
    elevation: 5,
  },
  textCheck: {
    color: color.secondary,
    letterSpacing: 2,
    fontWeight: font.h2.fontWeight,
    fontSize: font.b1.fontSize,
  },
  containerTextCheck: {
    backgroundColor: color.primary,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: widthScreen * 0.7,
    height: heightScreen * 0.032,
    borderTopEndRadius: 10,
    borderTopStartRadius: 10,
    paddingHorizontal: 10,
  },
  containerTextCheck2: {
    backgroundColor: color.primary,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: widthScreen * 0.7,
    height: heightScreen * 0.032,
    borderTopEndRadius: 10,
    borderTopStartRadius: 10,
    paddingHorizontal: 10,
  },
  containerTextCheckClose: {
    backgroundColor: color.primary,
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    width: widthScreen * 0.7,
    height: heightScreen * 0.032,
    borderRadius: 10,
    paddingHorizontal: 10,
  },
  containerTextCheckClose2: {
    backgroundColor: color.primary,
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    width: widthScreen * 0.7,
    height: heightScreen * 0.032,
    borderRadius: 10,
    paddingHorizontal: 10,
  },

  labelCheck: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginStart: widthScreen * 0.07,
  },
  checkbox: { width: widthScreen * 0.32, margin: widthScreen * 0.03 },
  calendar: {
    borderRadius: 10,

    borderColor: color.primary,
    fontSize: font.b2.fontSize,
    borderWidth: 0.1,
  },
  timePicker: {},
  hour: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: widthScreen * 0.6,
    height: heightScreen * 0.035,
    backgroundColor: color.secondary,
    elevation: 5,
    borderRadius: 5,
    paddingHorizontal: widthScreen * 0.03,
    marginVertical: heightScreen * 0.01,
  },
  textHour: {
    color: color.greyType,
    fontSize: font.h3.fontSize,
  },
  dataText: {
    color: color.primary,
    fontSize: font.b1.fontSize,
    letterSpacing: 2,
  },
  containerData: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: color.secondary,
    width: widthScreen * 0.7,
    borderBottomEndRadius: 5,
    borderBottomStartRadius: 5,
    elevation: 5,
    zIndex: 1,
  },
  containerData2: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: color.secondary,
    width: widthScreen * 0.7,
    borderBottomEndRadius: 5,
    borderBottomStartRadius: 5,
    elevation: 5,
    zIndex: 1,
  },
});

export default FormTrainingStyles;
